export default {
  Basics: {
    Basic: require(`./Basics/Basic.js`),
    Click: require(`./Basics/Click.js`),
    Container: require(`./Basics/Container.js`),
    ContainerPivot: require(`./Basics/ContainerPivot.js`),
    CustomFilter: require(`./Basics/CustomFilter.js`),
    Graphics: require(`./Basics/Graphics.js`),
    RenderTexture: require(`./Basics/RenderTexture.js`),
    SpriteSheetAnimation: require(`./Basics/SpriteSheetAnimation.js`),
    Text: require(`./Basics/Text.js`),
    TexturedMesh: require(`./Basics/TexturedMesh.js`),
    TilingSprite: require(`./Basics/TilingSprite.js`),
    Video: require(`./Basics/Video.js`),
  },
  Demos: {
    AlphaMask: require(`./Demos/AlphaMask.js`),
    AnimatedSprite: require(`./Demos/AnimatedSprite.js`),
    BlendModes: require(`./Demos/BlendModes.js`),
    CacheAsBitmap: require(`./Demos/CacheAsBitmap.js`),
    Dragging: require(`./Demos/Dragging.js`),
    Graphics: require(`./Demos/Graphics.js`),
    Interactivity: require(`./Demos/Interactivity.js`),
    MaskPlusRenderTexture: require(`./Demos/MaskPlusRenderTexture.js`),
    Masking: require(`./Demos/Masking.js`),
    ParticleContainer: require(`./Demos/ParticleContainer.js`),
    RenderTexture: require(`./Demos/RenderTexture.js`),
    Strip: require(`./Demos/Strip.js`),
    Text: require(`./Demos/Text.js`),
    TextureRotate: require(`./Demos/TextureRotate.js`),
    TextureSwap: require(`./Demos/TextureSwap.js`),
    Tinting: require(`./Demos/Tinting.js`),
    TransparentBackground: require(`./Demos/TransparentBackground.js`),
  },
  Display: {
    ZOrder: require(`./Display/ZOrder.js`),
  },
  Filters: {
    Blur: require(`./Filters/Blur.js`),
    DisplacementMap: require(`./Filters/DisplacementMap.js`),
    Filter: require(`./Filters/Filter.js`),
    MouseBlending: require(`./Filters/MouseBlending.js`),
    Outline: require(`./Filters/Outline.js`),
  },
  Layers: {
    Lighting: require(`./Layers/Lighting.js`),
    ZOrder: require(`./Layers/ZOrder.js`),
  },
  Picture: {
    OverlayBlendmode: require(`./Picture/OverlayBlendmode.js`),
  },
  Projection: {
    Basic: require(`./Projection/Basic.js`),
    Plane: require(`./Projection/Plane.js`),
    QuadBilinear: require(`./Projection/QuadBilinear.js`),
    QuadProjective: require(`./Projection/QuadProjective.js`),
  },
  Spine: {
    Dragon: require(`./Spine/Dragon.js`),
    Goblin: require(`./Spine/Goblin.js`),
    Pixie: require(`./Spine/Pixie.js`),
    WalkingAnimation: require(`./Spine/WalkingAnimation.js`),
  },
  Textures: {
    ExtensionChooser: require(`./Textures/ExtensionChooser.js`),
    NotPremultipliedAlpha: require(`./Textures/NotPremultipliedAlpha.js`),
  },
};
