# Useful resource: https://github.com/actions/starter-workflows

name: Check Universal Module

on:
  workflow_dispatch: {}
  push:
    branches:
      # If this isn't defined then all PR tests will be run twice
      - master
    paths:
      - '*'
      - '.github/workflows/Module.yml'
      - '!*.md'
  pull_request:
    paths:
      - '*'
      - '.github/workflows/Module.yml'
      - '!*.md'

jobs:
  test:
    name: Check Universal Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      - name: Check Package
        run: ./scripts/module-scripts-check-package.sh
